server:
  port: 3355

spring:
  application:
    name: config-client
  cloud:
    #config客户端配置
    config:
      label: master #分支名称
      name: config #配置文件名称
      profile: dev #读取后缀名称，上述3个综合：master分支上config-dev。xml的配置文件被读取http://config-3344.com:3344/master/cofig-dev.xml
      uri: http://localhost:3344 #配置中心地址
eureka:
  client:
    service-url:
      defaultZone: http://eureka7001.com:7001/eureka

#暴露监控端口
management:
  endpoints:
    web:
      exposure:
        include: "*"