server:
  port: 8002


spring:
  application:
    name: cloud-payment-service
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: org.gjt.mm.mysql.Driver
    #url: jdbc:mysql://localhost:3306/db2019?useUnicode=true&characterEncoding=utf-8&useSSL=false
    url: jdbc:mysql://localhost:3306/db2019
    username: root
    password: admin
    druid:
      validation-query: select 1
      test-while-idle: true
      test-on-borrow: false
      test-on-return: false

#eurka配置
eureka:
  client:
    register-with-eureka: true  #true表示向注册中心注册自己
    #是否从EurekaServer抓取已有的注册信息,默认是true,单节点无所谓,集群必须设置为true才能配合ribbon使用负载均衡
    fetchRegistry: true
    service-url:
      #defaultZone: http://localhost:7001/eureka
      defaultZone: http://eureka7001.com:7001/eureka,http://eureka7002.com:7002/eureka  #集群版
  instance:
    instance-id: payment8002  #修改主机服务名称
    prefer-ip-address: true #访问路径可以显示ip地址

mybatis:
  mapperLocations: classpath:mapper/*.xml
  type-aliases-package: com.atguigu.springcloud.entities


