server:
  port: 7001

eureka:
  instance:
    hostname: eureka7001.com  #eureka服务端的实例名字
  client:
    register-with-eureka: false    #false表识不向注册中心注册自己
    fetch-registry: false   #false表示自己就是注册中心，职责是维护服务实例，并不需要去检索服务
    service-url:
        #集群指向其他Eureka
        #defaultZone: http://eureka7002.com:7002/eureka/    #设置与eureka server交互的地址查询服务和注册服务都需要依赖这个地址
        #单机就是指向7001自己
        defaultZone: http://eureka7001.com:7001/eureka/
  #关闭自我保护机制,保证不可用服务及时被提出,默认不关闭,生产环境一般是不关闭的
  #server:
  #  enable-self-preservation: false
  #  eviction-interval-timer-in-ms: 2000

